<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<div class="block newsletter block-subscribe">
        <form class="form subscribe clearfix"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
			<div class="block-content">
				<div class="container">
					 <div class="block-title">
						<h3><?php echo __('NEWSLETTER SIGNUP') ?></h3>
						<p>subscribe to our newsletter or register a customer account and get 10% off your first purchase</p>
					 </div>
					<div class="form-subscribe-header">
						<span class="title-label-newsletter"><?php echo __('Subscribe for Our Newsletter') ?></span>
					</div>
					<div class="field newsletter input-box">
						<div class="visible">
							<div class="control">
								<input name="email" type="email" id="newsletter" class="input-text"
									placeholder="<?php /* @escapeNotVerified */ echo __('Your Email Address') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
							</div>
							<div class="actions">
								<button class="action subscribe button" title="<?php /* @escapeNotVerified */ echo __('Subscribe Now') ?>" type="submit">
									<span><?php /* @escapeNotVerified */ echo __('Subscribe Now') ?></span>
								</button>
							</div>
						</div>
					</div>
			</div>
			</div>
        </form>
</div>
